services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: codebot-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-8082}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: codebot-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-3002}:${PORT:-3002}"
    environment:
      - PORT=${PORT:-3002}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - ./.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge